# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 22:22
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
                ('estimate', models.FloatField(blank=True, null=True)),
                ('color', core.fields.ColorField(max_length=7)),
                ('last_started', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('focused', 'Focused'), ('client', 'Client')], default='focused', max_length=10)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.Bucket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('amount', models.PositiveIntegerField()),
                ('fresh_start', models.BooleanField(default=False)),
                ('bucket', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='DayCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_json', models.TextField()),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='core.DayCache')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('bucket', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bucket')),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailytarget',
            unique_together=set([('date', 'bucket')]),
        ),
    ]
