# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 20:36
from __future__ import unicode_literals

import colorful.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, null=True)),
                ('estimate', models.IntegerField(blank=True, null=True)),
                ('color', colorful.fields.RGBColorField(colors=['#92a8d1', '#034f84', '#f7cac9', '#f7786b', '#deeaee', '#b1cbbb', '#eea29a', '#c94c4c', '#d5f4e6', '#80ced6', '#fefbd8', '#618685', '#ffef96', '#50394c', '#b2b2b2', '#f4e1d2', '#fefbd8', '#618685', '#36486b', '#4040a1', '#b2b2b2', '#f4e1d2', '#f18973', '#bc5a45', '#f0f0f0', '#c5d5c5', '#9fa9a3', '#e3e0cc', '#eaece5', '#b2c2bf', '#c0ded9', '#3b3a30', '#e4d1d1', '#b9b0b0', '#d9ecd0', '#77a8a8', '#f0efef', '#ddeedd', '#c2d4dd', '#b0aac0', '#c8c3cc', '#563f46', '#8ca3a3', '#484f4f', '#e0e2e4', '#c6bcb6', '#96897f', '#625750', '#bccad6', '#8d9db6', '#667292', '#f1e3dd', '#cfe0e8', '#b7d7e8', '#87bdd8', '#daebe8', '#fbefcc', '#f9ccac', '#f4a688', '#e0876a', '#fff2df', '#d9ad7c', '#a2836e', '#674d3c', '#f9d5e5', '#eeac99', '#e06377', '#c83349', '#5b9aa0', '#d6d4e0', '#b8a9c9', '#622569', '#96ceb4', '#ffeead', '#ffcc5c', '#ff6f69', '#588c7e', '#f2e394', '#f2ae72', '#d96459'])),
                ('last_started', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('focused', 'Focused'), ('other', 'Other')], default='focused', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('work_starts', models.TimeField(blank=True, default='09:00', null=True)),
                ('work_ends', models.TimeField(blank=True, default='17:00', null=True)),
                ('worked', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=102400, null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bucket')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Day')),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.AddField(
            model_name='bucket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
    ]
