# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='worked',
        ),
    ]
