# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_day_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='estimate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
